import React, { useState } from 'react';
import { Download, FileJson, FileSpreadsheet, FileText, Loader2 } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { toast } from 'sonner';
import jsPDF from 'jspdf';
import * as XLSX from 'xlsx';

interface ExportReportProps {
  projectId: string;
  projectName: string;
  projectData: {
    code?: string;
    status?: string;
    health?: string;
    overallProgress?: number;
    totalBudget?: number;
    spent?: number;
    startDate?: string;
    endDate?: string;
    phases?: Array<{ name: string; progress: number }>;
  };
}

export const ExportReport: React.FC<ExportReportProps> = ({
  projectId,
  projectName,
  projectData,
}) => {
  const [exporting, setExporting] = useState<string | null>(null);

  const exportToPDF = async () => {
    setExporting('pdf');
    try {
      const doc = new jsPDF();
      let yPosition = 20;

      // Header
      doc.setFontSize(20);
      doc.setTextColor(0, 0, 0);
      doc.text('Project Report', 20, yPosition);
      yPosition += 15;

      // Project Name
      doc.setFontSize(16);
      doc.text(projectName, 20, yPosition);
      yPosition += 10;

      // Metadata
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text(`Project ID: ${projectId}`, 20, yPosition);
      yPosition += 5;
      doc.text(`Code: ${projectData.code || 'N/A'}`, 20, yPosition);
      yPosition += 5;
      doc.text(`Generated: ${new Date().toLocaleDateString()}`, 20, yPosition);
      yPosition += 15;

      // Status Section
      doc.setFontSize(14);
      doc.setTextColor(0, 0, 0);
      doc.text('Project Status', 20, yPosition);
      yPosition += 8;
      
      doc.setFontSize(10);
      doc.text(`Status: ${projectData.status || 'In Progress'}`, 25, yPosition);
      yPosition += 5;
      doc.text(`Health: ${projectData.health || 'Good'}`, 25, yPosition);
      yPosition += 5;
      doc.text(`Progress: ${projectData.overallProgress || 0}%`, 25, yPosition);
      yPosition += 15;

      // Budget Section
      doc.setFontSize(14);
      doc.text('Budget Information', 20, yPosition);
      yPosition += 8;
      
      doc.setFontSize(10);
      const totalBudget = projectData.totalBudget || 0;
      const spent = projectData.spent || 0;
      doc.text(`Total Budget: ${totalBudget.toLocaleString()} DZD`, 25, yPosition);
      yPosition += 5;
      doc.text(`Spent: ${spent.toLocaleString()} DZD`, 25, yPosition);
      yPosition += 5;
      doc.text(`Remaining: ${(totalBudget - spent).toLocaleString()} DZD`, 25, yPosition);
      yPosition += 5;
      doc.text(`Usage: ${totalBudget > 0 ? Math.round((spent / totalBudget) * 100) : 0}%`, 25, yPosition);
      yPosition += 15;

      // Schedule Section
      doc.setFontSize(14);
      doc.text('Schedule', 20, yPosition);
      yPosition += 8;
      
      doc.setFontSize(10);
      doc.text(`Start Date: ${projectData.startDate || 'N/A'}`, 25, yPosition);
      yPosition += 5;
      doc.text(`End Date: ${projectData.endDate || 'N/A'}`, 25, yPosition);
      yPosition += 15;

      // Phases Section
      if (projectData.phases && projectData.phases.length > 0) {
        doc.setFontSize(14);
        doc.text('Phases', 20, yPosition);
        yPosition += 8;
        
        doc.setFontSize(10);
        projectData.phases.forEach((phase) => {
          doc.text(`• ${phase.name}: ${phase.progress}%`, 25, yPosition);
          yPosition += 5;
        });
      }

      // Footer
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text('Generated by LightPro Project Management System', 20, 280);

      // Save PDF
      doc.save(`${projectName.replace(/\s+/g, '_')}_report.pdf`);
      toast.success('PDF exported successfully');
    } catch (error) {
      console.error('PDF export failed:', error);
      toast.error('Failed to export PDF');
    } finally {
      setExporting(null);
    }
  };

  const exportToExcel = () => {
    setExporting('excel');
    try {
      const totalBudget = projectData.totalBudget || 0;
      const spent = projectData.spent || 0;

      const worksheetData = [
        ['Project Report - ' + projectName],
        [],
        ['General Information'],
        ['Project Name', projectName],
        ['Project ID', projectId],
        ['Project Code', projectData.code || 'N/A'],
        ['Generated Date', new Date().toLocaleDateString()],
        [],
        ['Status Information'],
        ['Status', projectData.status || 'In Progress'],
        ['Health', projectData.health || 'Good'],
        ['Progress', `${projectData.overallProgress || 0}%`],
        [],
        ['Budget Information'],
        ['Total Budget', `${totalBudget.toLocaleString()} DZD`],
        ['Spent', `${spent.toLocaleString()} DZD`],
        ['Remaining', `${(totalBudget - spent).toLocaleString()} DZD`],
        ['Usage', `${totalBudget > 0 ? Math.round((spent / totalBudget) * 100) : 0}%`],
        [],
        ['Schedule'],
        ['Start Date', projectData.startDate || 'N/A'],
        ['End Date', projectData.endDate || 'N/A'],
      ];

      // Add phases if available
      if (projectData.phases && projectData.phases.length > 0) {
        worksheetData.push([]);
        worksheetData.push(['Phases']);
        worksheetData.push(['Phase Name', 'Progress']);
        projectData.phases.forEach((phase) => {
          worksheetData.push([phase.name, `${phase.progress}%`]);
        });
      }

      const worksheet = XLSX.utils.aoa_to_sheet(worksheetData);
      
      // Set column widths
      worksheet['!cols'] = [{ wch: 20 }, { wch: 30 }];

      const workbook = XLSX.utils.book_new();
      XLSX.utils.book_append_sheet(workbook, worksheet, 'Report');
      XLSX.writeFile(workbook, `${projectName.replace(/\s+/g, '_')}_report.xlsx`);
      toast.success('Excel exported successfully');
    } catch (error) {
      console.error('Excel export failed:', error);
      toast.error('Failed to export Excel');
    } finally {
      setExporting(null);
    }
  };

  const exportToJSON = () => {
    setExporting('json');
    try {
      const exportData = {
        projectId,
        projectName,
        generatedAt: new Date().toISOString(),
        ...projectData,
      };

      const dataStr = JSON.stringify(exportData, null, 2);
      const dataUri = 'data:application/json;charset=utf-8,' + encodeURIComponent(dataStr);
      const exportFileDefaultName = `${projectName.replace(/\s+/g, '_')}_data.json`;

      const linkElement = document.createElement('a');
      linkElement.setAttribute('href', dataUri);
      linkElement.setAttribute('download', exportFileDefaultName);
      linkElement.click();
      toast.success('JSON exported successfully');
    } catch (error) {
      console.error('JSON export failed:', error);
      toast.error('Failed to export JSON');
    } finally {
      setExporting(null);
    }
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Download className="w-5 h-5" />
          Export Project Report
        </CardTitle>
      </CardHeader>
      <CardContent>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {/* PDF Export */}
          <Button
            onClick={exportToPDF}
            disabled={exporting !== null}
            variant="outline"
            className="h-auto py-4 flex flex-col items-center gap-2 bg-red-50 dark:bg-red-950/30 border-red-200 dark:border-red-800 text-red-700 dark:text-red-400 hover:bg-red-100 dark:hover:bg-red-950/50"
          >
            {exporting === 'pdf' ? (
              <Loader2 className="w-6 h-6 animate-spin" />
            ) : (
              <FileText className="w-6 h-6" />
            )}
            <span className="font-medium">Export PDF</span>
            <span className="text-xs opacity-70">Formatted report</span>
          </Button>

          {/* Excel Export */}
          <Button
            onClick={exportToExcel}
            disabled={exporting !== null}
            variant="outline"
            className="h-auto py-4 flex flex-col items-center gap-2 bg-emerald-50 dark:bg-emerald-950/30 border-emerald-200 dark:border-emerald-800 text-emerald-700 dark:text-emerald-400 hover:bg-emerald-100 dark:hover:bg-emerald-950/50"
          >
            {exporting === 'excel' ? (
              <Loader2 className="w-6 h-6 animate-spin" />
            ) : (
              <FileSpreadsheet className="w-6 h-6" />
            )}
            <span className="font-medium">Export Excel</span>
            <span className="text-xs opacity-70">Spreadsheet data</span>
          </Button>

          {/* JSON Export */}
          <Button
            onClick={exportToJSON}
            disabled={exporting !== null}
            variant="outline"
            className="h-auto py-4 flex flex-col items-center gap-2 bg-primary/10 border-primary/20 text-primary hover:bg-primary/20"
          >
            {exporting === 'json' ? (
              <Loader2 className="w-6 h-6 animate-spin" />
            ) : (
              <FileJson className="w-6 h-6" />
            )}
            <span className="font-medium">Export JSON</span>
            <span className="text-xs opacity-70">Raw data</span>
          </Button>
        </div>

        <div className="mt-4 p-3 bg-muted rounded-lg">
          <p className="text-xs text-muted-foreground">
            💡 <strong>Pro Tip:</strong> Export reports to share with stakeholders or archive project documentation.
          </p>
        </div>
      </CardContent>
    </Card>
  );
};

export default ExportReport;
